/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:a4aef3da-86c6-4593-a058-5dedd3681f11",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_AIFSOjtz1",
    "aws_user_pools_web_client_id": "7en3et1ntkuk48aamvq38ffgs",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://7bmyqojxo5f6tjdrj3zzoqvqgu.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hwzezagd6jb4rcstgb74ryiuo4",
    "aws_user_files_s3_bucket": "learnreactbackend233352-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
